# Generated by Django 5.0.4 on 2024-04-29 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(upload_to='')),
                ('publisher', models.CharField(max_length=20)),
                ('Telephone', models.BigIntegerField(blank=True, null=True)),
                ('color', models.CharField(choices=[('white', 'white'), ('black', 'black'), ('red', 'red'), ('blue', 'blue'), ('green', 'green')], max_length=20)),
            ],
            options={
                'db_table': 'Notebook',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code_meli', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('Address', models.CharField(max_length=200)),
                ('Telephone', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('unit_no', models.IntegerField(blank=True, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_order', models.CharField(choices=[('Accepted', 'Accepted'), ('not confirmed', 'not confirmed'), ('pending', 'pending')], default=False)),
                ('date_order', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='book.customer')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exist', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='book.notebook')),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='book.order')),
                ('notebooks', models.ManyToManyField(to='book.store')),
            ],
            options={
                'db_table': 'Order_Item',
            },
        ),
    ]
