# Generated by Django 5.0.4 on 2024-04-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebook',
            old_name='Telephone',
            new_name='page_number',
        ),
    ]
