# Generated by Django 5.0.4 on 2024-04-28 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(upload_to='')),
                ('publisher', models.CharField(max_length=20)),
                ('Telephone', models.BigIntegerField(blank=True, null=True)),
                ('color', models.CharField(choices=[('white', 'white'), ('black', 'black'), ('red', 'red'), ('blue', 'blue'), ('green', 'green')], max_length=20)),
            ],
            options={
                'db_table': 'Notebook',
            },
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='sum_price',
        ),
        migrations.AddField(
            model_name='order_item',
            name='item',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='item', to='book.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status_order',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('not confirmed', 'not confirmed'), ('pending', 'pending')], default=False),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exist', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='book.notebook')),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.AddField(
            model_name='order_item',
            name='storeproduct',
            field=models.ManyToManyField(to='book.store'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
