# Generated by Django 5.0.4 on 2024-04-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_telephone_notebook_page_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='page_number',
            field=models.BigIntegerField(blank=True, choices=[('white', '40'), ('black', '60'), ('red', '80'), ('blue', '100'), ('green', '200')], null=True),
        ),
    ]
