# Generated by Django 5.0.4 on 2024-04-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_notebook_page_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
