# Generated by Django 5.0.4 on 2024-04-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_notebook_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='exist',
        ),
        migrations.AddField(
            model_name='store',
            name='count',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='is_exist',
            field=models.BooleanField(default=False),
        ),
    ]
